# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QHBoxLayout,
    QLCDNumber, QLabel, QMainWindow, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QSlider,
    QStatusBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1768, 828)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.update = QPushButton(self.centralwidget)
        self.update.setObjectName(u"pushButton")
        self.update.setGeometry(QRect(20, 20, 75, 75))
        self.initiate = QPushButton(self.centralwidget)
        self.initiate.setObjectName(u"initiate")
        self.initiate.setGeometry(QRect(120, 20, 75, 75))
        self.calibrate = QPushButton(self.centralwidget)
        self.calibrate.setObjectName(u"calibrate")
        self.calibrate.setGeometry(QRect(220, 20, 75, 75))
        self.start = QPushButton(self.centralwidget)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(320, 20, 75, 75))
        self.pause = QPushButton(self.centralwidget)
        self.pause.setObjectName(u"pause")
        self.pause.setGeometry(QRect(420, 20, 75, 75))
        self.stop = QPushButton(self.centralwidget)
        self.stop.setObjectName(u"stop")
        self.stop.setGeometry(QRect(520, 20, 75, 75))
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(20, 110, 275, 350))
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(320, 110, 275, 350))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.lcdNumber = QLCDNumber(self.frame)
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.lcdNumber.setGeometry(QRect(190, 20, 65, 25))
        self.lcdNumber_2 = QLCDNumber(self.frame)
        self.lcdNumber_2.setObjectName(u"lcdNumber_2")
        self.lcdNumber_2.setGeometry(QRect(190, 60, 65, 25))
        self.lcdNumber_3 = QLCDNumber(self.frame)
        self.lcdNumber_3.setObjectName(u"lcdNumber_3")
        self.lcdNumber_3.setGeometry(QRect(190, 140, 65, 25))
        self.lcdNumber_4 = QLCDNumber(self.frame)
        self.lcdNumber_4.setObjectName(u"lcdNumber_4")
        self.lcdNumber_4.setGeometry(QRect(190, 100, 65, 25))
        self.lcdNumber_5 = QLCDNumber(self.frame)
        self.lcdNumber_5.setObjectName(u"lcdNumber_5")
        self.lcdNumber_5.setGeometry(QRect(190, 220, 65, 25))
        self.lcdNumber_6 = QLCDNumber(self.frame)
        self.lcdNumber_6.setObjectName(u"lcdNumber_6")
        self.lcdNumber_6.setGeometry(QRect(190, 260, 65, 25))
        self.lcdNumber_7 = QLCDNumber(self.frame)
        self.lcdNumber_7.setObjectName(u"lcdNumber_7")
        self.lcdNumber_7.setGeometry(QRect(190, 180, 65, 25))
        self.lcdNumber_8 = QLCDNumber(self.frame)
        self.lcdNumber_8.setObjectName(u"lcdNumber_8")
        self.lcdNumber_8.setGeometry(QRect(190, 300, 65, 25))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 23, 141, 17))
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 63, 151, 17))
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 143, 151, 17))
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 103, 141, 17))
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 183, 141, 17))
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 223, 141, 17))
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 263, 141, 17))
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 303, 141, 17))
        self.graphicsView_2 = QGraphicsView(self.centralwidget)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(630, 70, 700, 400))
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(630, 20, 701, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.rgbdbutton = QRadioButton(self.horizontalLayoutWidget)
        self.rgbdbutton.setObjectName(u"rgbdbutton")

        self.horizontalLayout.addWidget(self.rgbdbutton)

        self.lidarbutton = QRadioButton(self.horizontalLayoutWidget)
        self.lidarbutton.setObjectName(u"lidarbutton")

        self.horizontalLayout.addWidget(self.lidarbutton)

        self.traject2dbutton = QRadioButton(self.horizontalLayoutWidget)
        self.traject2dbutton.setObjectName(u"traject2dbutton")

        self.horizontalLayout.addWidget(self.traject2dbutton)

        self.traject3dbutton = QRadioButton(self.horizontalLayoutWidget)
        self.traject3dbutton.setObjectName(u"traject3dbutton")

        self.horizontalLayout.addWidget(self.traject3dbutton)

        self.lcdNumber_9 = QLCDNumber(self.centralwidget)
        self.lcdNumber_9.setObjectName(u"lcdNumber_9")
        self.lcdNumber_9.setGeometry(QRect(1270, 80, 64, 23))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(1230, 83, 31, 17))
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(20, 480, 411, 171))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_10 = QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName(u"label_10")

        self.verticalLayout.addWidget(self.label_10)

        self.horizontalSlider = QSlider(self.verticalLayoutWidget)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setOrientation(Qt.Horizontal)

        self.verticalLayout.addWidget(self.horizontalSlider)

        self.label_12 = QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName(u"label_12")

        self.verticalLayout.addWidget(self.label_12)

        self.horizontalSlider_3 = QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_3.setObjectName(u"horizontalSlider_3")
        self.horizontalSlider_3.setOrientation(Qt.Horizontal)

        self.verticalLayout.addWidget(self.horizontalSlider_3)

        self.label_11 = QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName(u"label_11")

        self.verticalLayout.addWidget(self.label_11)

        self.horizontalSlider_2 = QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_2.setObjectName(u"horizontalSlider_2")
        self.horizontalSlider_2.setOrientation(Qt.Horizontal)

        self.verticalLayout.addWidget(self.horizontalSlider_2)

        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(950, 490, 75, 75))
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(950, 650, 75, 75))
        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(870, 570, 75, 75))
        self.pushButton_10 = QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(1030, 570, 75, 75))
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(1130, 490, 201, 231))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_13 = QLabel(self.frame_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 30, 101, 17))
        self.lcdNumber_10 = QLCDNumber(self.frame_2)
        self.lcdNumber_10.setObjectName(u"lcdNumber_10")
        self.lcdNumber_10.setGeometry(QRect(130, 28, 64, 23))
        self.lcdNumber_11 = QLCDNumber(self.frame_2)
        self.lcdNumber_11.setObjectName(u"lcdNumber_11")
        self.lcdNumber_11.setGeometry(QRect(130, 68, 64, 23))
        self.label_14 = QLabel(self.frame_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 70, 101, 17))
        self.lcdNumber_12 = QLCDNumber(self.frame_2)
        self.lcdNumber_12.setObjectName(u"lcdNumber_12")
        self.lcdNumber_12.setGeometry(QRect(130, 108, 64, 23))
        self.label_15 = QLabel(self.frame_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 110, 101, 17))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1768, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.stop, self.start)
        QWidget.setTabOrder(self.start, self.pause)
        QWidget.setTabOrder(self.pause, self.calibrate)
        QWidget.setTabOrder(self.calibrate, self.initiate)
        QWidget.setTabOrder(self.initiate, self.graphicsView)
        QWidget.setTabOrder(self.graphicsView, self.update)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.update.setText(QCoreApplication.translate("MainWindow", u"Update", None))
        self.initiate.setText(QCoreApplication.translate("MainWindow", u"Initiate", None))
        self.calibrate.setText(QCoreApplication.translate("MainWindow", u"Calibrate", None))
        self.start.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.pause.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Front Left Motor (V)", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Front Right Motor (V)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Back Right Motor (V)", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Back Left Motor (V)", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Jetson Module (V)", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Arduino Module (V)", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"LiDAR Module (V)", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Battery (V)", None))
        self.rgbdbutton.setText(QCoreApplication.translate("MainWindow", u"RGB-D Camera", None))
        self.lidarbutton.setText(QCoreApplication.translate("MainWindow", u"3D-LiDAR Vision", None))
        self.traject2dbutton.setText(QCoreApplication.translate("MainWindow", u"Trajectory 2D Vision", None))
        self.traject3dbutton.setText(QCoreApplication.translate("MainWindow", u"Trajectory 3D Vision", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"FPS", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Max Speed (m/s)", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Min Speed (m/s)", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Max Angular Speed (\u00b1rad/s)", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Forward", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Backward", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Left", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Right", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Speed", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Angular Speed", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Heading (deg)", None))
    # retranslateUi

